# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDNetworkHelper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WDNetworkHelper

  target 'WDNetworkHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'YYCache'
end
